# Namn på din organisation
org: ${env:ORG}
# Namnet på din tjänst
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/bonzai

# Funktioner (Lambda)
functions:
  GetBookings:
    handler: functions/GetBookings/index.handler
    events:
      - httpApi:
          # ÄNDRAD: Mer specifik sökväg för att hämta bokningar
          path: /bookings
          method: get

  BookRoom:
    handler: functions/BookRoom/index.handler
    events:
      - httpApi:
          # ÄNDRAD: Samma sökväg som GET, men POST för att skapa nytt
          path: /bookings
          method: post

  ChangeBooking:
    handler: functions/ChangeBooking/index.handler
    events:
      - httpApi:
          # ÄNDRAD: Sökväg för att ändra en specifik bokning via dess ID
          path: /bookings/{id}
          method: put

  DeleteBooking:
    handler: functions/DeleteBooking/index.handler
    events:
      - httpApi:
          # ÄNDRAD: Sökväg för att radera en specifik bokning via dess ID
          path: /bookings/{id}
          method: delete

# AWS-infrastruktur
resources:
  Resources:
    BonzaiTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: bonzai
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
